"""
seed_questions.py — Populates the question_bank table with 113 questions across 12 phases.

Questions synthesized from Robinson (Big Idea), Chapell (FCF/Christ-Centered Preaching),
Edwards (Affections), Perkins (practical uses), York, and Greidanus (Christ-Centered OT).
"""

QUESTIONS = [
    # ── PRAYER (Phase 1) — single card, one act of spiritual preparation ──
    {"phase": "prayer", "question_text": "Pray before you study.",
     "guidance_text": "Ask the Holy Spirit to guard your easily distracted mind. Come as a worshiper, not a technician. What fears, sins, or doubts might this text address in you?", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 1},

    # ── TEXT WORK (Phase 2) ──
    {"phase": "text_work", "question_text": "What is my own working translation of this text?",
     "guidance_text": "Not a published translation — yours. Work from the original language.", "genre_tags": "[]",
     "priority": "core", "resource_type": "original_lang", "rank": 1},
    {"phase": "text_work", "question_text": "Are there any textual variants that affect meaning?",
     "guidance_text": "Check critical apparatus or textual notes.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 2},
    {"phase": "text_work", "question_text": "Where does the pericope begin and end? What markers signal the boundaries?",
     "guidance_text": "Discourse markers, change of scene, shift in audience, inclusio, chiasm.", "genre_tags": "[]",
     "priority": "core", "resource_type": "bible", "rank": 3},
    {"phase": "text_work", "question_text": "Were there any really odd words?",
     "guidance_text": "Words that seem out of place or unexpected in context.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 4},
    {"phase": "text_work", "question_text": "Was there repetition?",
     "guidance_text": "Repeated words, phrases, or structures often signal emphasis.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 5},
    {"phase": "text_work", "question_text": "Were there any references to other texts?",
     "guidance_text": "OT allusions, quotations, intertextual echoes.", "genre_tags": "[]",
     "priority": "core", "resource_type": "cross_ref", "rank": 6},
    {"phase": "text_work", "question_text": "What is the main verb? What is its tense/aspect/mood?",
     "guidance_text": "The main verb carries the weight of the clause.", "genre_tags": '["epistle","narrative","prophecy","law"]',
     "priority": "core", "resource_type": "interlinear", "rank": 7},
    {"phase": "text_work", "question_text": "What is the grammatical subject?",
     "guidance_text": "Who or what is doing the action?", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "interlinear", "rank": 8},
    {"phase": "text_work", "question_text": "What are the subordinate clauses, and what logical relationship do they express?",
     "guidance_text": "Cause, result, purpose, condition, concession, means.", "genre_tags": '["epistle"]',
     "priority": "supplemental", "resource_type": "none", "rank": 9},
    {"phase": "text_work", "question_text": "Are there participles? What kind?",
     "guidance_text": "Adverbial (temporal, causal, concessive, conditional) or adjectival/substantival.", "genre_tags": '["epistle"]',
     "priority": "supplemental", "resource_type": "interlinear", "rank": 10},
    {"phase": "text_work", "question_text": "Is there figurative language? What type?",
     "guidance_text": "Metaphor, simile, hyperbole, metonymy, synecdoche, irony.", "genre_tags": '["poetry","prophecy","wisdom"]',
     "priority": "core", "resource_type": "none", "rank": 11},
    {"phase": "text_work", "question_text": "What is the literary type/genre of this unit?",
     "guidance_text": "Narrative, discourse, poetry, prophecy, apocalyptic, parable, law.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 12},
    {"phase": "text_work", "question_text": "What grammatical constructions are significant?",
     "guidance_text": "Chiasm, inclusio, parallelism, word order emphasis.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 13},

    # ── DIGESTION (Phase 3) ──
    {"phase": "digestion", "question_text": "Can I write a prayer for each phrase/sentence/paragraph of the text?",
     "guidance_text": "Devotional engagement — pray through the text phrase by phrase.", "genre_tags": "[]",
     "priority": "core", "resource_type": "bible", "rank": 1},

    # ── OBSERVATION (Phase 4) ──
    {"phase": "observation", "question_text": "WHO — Who is speaking? Who is being addressed? Who else is present?",
     "guidance_text": "What is the reader expected to know about them?", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 1},
    {"phase": "observation", "question_text": "WHAT — What action is taking place? What command, promise, or warning is given?",
     "guidance_text": "Identify the main action or speech act.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 2},
    {"phase": "observation", "question_text": "WHEN — What temporal markers exist? Where is this in redemptive history?",
     "guidance_text": "Temporal setting and redemptive-historical location.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 3},
    {"phase": "observation", "question_text": "WHERE — What is the geographic setting? Does the location carry theological significance?",
     "guidance_text": "Wilderness, temple, Babylon, Jerusalem — places with meaning.", "genre_tags": '["narrative"]',
     "priority": "core", "resource_type": "none", "rank": 4},
    {"phase": "observation", "question_text": "WHY — Why is this detail included at this point?",
     "guidance_text": "Why did the character say or do this?", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 5},
    {"phase": "observation", "question_text": "HOW — How does this unit relate to what comes before and after?",
     "guidance_text": "How does the argument or narrative progress?", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 6},
    {"phase": "observation", "question_text": "Was this expected/acceptable behavior at the time?",
     "guidance_text": "Cultural norms the original audience would recognize.", "genre_tags": '["narrative"]',
     "priority": "supplemental", "resource_type": "none", "rank": 7},
    {"phase": "observation", "question_text": "What might be the original audience's visceral reaction to this?",
     "guidance_text": "Put yourself in their shoes.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 8},
    {"phase": "observation", "question_text": "Are there cultural things that color this — customs, social dynamics, economics, politics?",
     "guidance_text": "Background that shapes meaning.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 9},
    {"phase": "observation", "question_text": "What would a first-century (or ancient) hearer understand that a modern audience would miss?",
     "guidance_text": "The gap between then and now.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 10},

    # ── WORD STUDY (Phase 5) ──
    {"phase": "word_study", "question_text": "Which words in this passage carry theological weight?",
     "guidance_text": "Words that, if changed, would fundamentally shift the meaning. Identify 2-4 max.", "genre_tags": "[]",
     "priority": "core", "resource_type": "interlinear", "rank": 1},
    {"phase": "word_study", "question_text": "What is the semantic range of each key term?",
     "guidance_text": "What does it mean elsewhere in this author's writings? In this Testament? In the LXX?", "genre_tags": "[]",
     "priority": "core", "resource_type": "interlinear", "rank": 2},
    {"phase": "word_study", "question_text": "Is this a technical term?",
     "guidance_text": "E.g., dikaiosyne, hesed, berith, hilasterion, logos, sarx.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 3},
    {"phase": "word_study", "question_text": "Does this word appear in a word group that matters?",
     "guidance_text": "E.g., pistis/pisteuo/pistos family.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 4},
    {"phase": "word_study", "question_text": "What is the etymological background — and does it actually matter here?",
     "guidance_text": "Beware the root fallacy. Usage in context trumps etymology.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 5},
    {"phase": "word_study", "question_text": "What lexicon entries illuminate the usage in context?",
     "guidance_text": "BDAG, HALOT, NIDNTTE, TDNT.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 6},
    {"phase": "word_study", "question_text": "Are there any hapax legomena or rare forms?",
     "guidance_text": "Words that appear only here require special attention.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 7},

    # ── CONTEXT (Phase 6) ──
    {"phase": "context", "question_text": "What comes directly before this pericope? What comes directly after?",
     "guidance_text": "Immediate context shapes interpretation.", "genre_tags": "[]",
     "priority": "core", "resource_type": "bible", "rank": 1},
    {"phase": "context", "question_text": "Are there surrounding units of thought that should be kept in mind?",
     "guidance_text": "Near context — the chapter, the section.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 2},
    {"phase": "context", "question_text": "How does this unit function within the argument/narrative of the chapter?",
     "guidance_text": "What role does this pericope play?", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 3},
    {"phase": "context", "question_text": "What is the point of this passage in the larger picture of this book?",
     "guidance_text": "Book-level context.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 4},
    {"phase": "context", "question_text": "What is the author's stated or implied purpose for writing this book?",
     "guidance_text": "The book's purpose shapes how each unit should be read.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 5},
    {"phase": "context", "question_text": "Where are we in the author's argument or narrative arc?",
     "guidance_text": "Beginning, middle, climax, resolution?", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 6},
    {"phase": "context", "question_text": "Where does this fit within the canonical and historical redemptive context?",
     "guidance_text": "The big story of Scripture.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 7},
    {"phase": "context", "question_text": "Is this passage referenced or quoted elsewhere in Scripture?",
     "guidance_text": "Does the NT give a hermeneutical lens for understanding it?", "genre_tags": "[]",
     "priority": "core", "resource_type": "cross_ref", "rank": 8},
    {"phase": "context", "question_text": "What parallel passages exist?",
     "guidance_text": "Synoptic parallels, Chronicles/Kings, Paul's repeated themes.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "cross_ref", "rank": 9},
    {"phase": "context", "question_text": "How does it fit with the complete unit of thought, book, or Bible?",
     "guidance_text": "Canonical context — the widest circle.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 10},

    # ── THEOLOGICAL (Phase 7) — includes 6A, 6B, 6C ──
    # 6A: Seven Roads to Christ
    {"phase": "theological", "question_text": "Promise-Fulfillment: Is there a messianic hope or promise fulfilled in Christ?",
     "guidance_text": "Greidanus Road 1.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 1},
    {"phase": "theological", "question_text": "Typology: Is there a person, action, event, or institution that prefigures Christ?",
     "guidance_text": "Greidanus Road 2. Look for escalation from type to antitype.", "genre_tags": '["narrative","law"]',
     "priority": "core", "resource_type": "none", "rank": 2},
    {"phase": "theological", "question_text": "Analogy: Are there parallel situations between God's work with Israel and God's work in Christ?",
     "guidance_text": "Greidanus Road 3.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 3},
    {"phase": "theological", "question_text": "Longitudinal Themes: What truth about God's saving work is disclosed here?",
     "guidance_text": "Greidanus Road 4. Key highways: Kingdom, covenant, providence, presence, love/grace/justice, redemption, law, sacrifice, mediator, Day of the Lord.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 4},
    {"phase": "theological", "question_text": "Contrast: What changes from Old Covenant to New in Christ?",
     "guidance_text": "Greidanus Road 5.", "genre_tags": '["law","prophecy"]',
     "priority": "supplemental", "resource_type": "none", "rank": 5},
    {"phase": "theological", "question_text": "NT Reference: Does the NT cite or allude to this passage?",
     "guidance_text": "Greidanus Road 6.", "genre_tags": '["narrative","poetry","prophecy","law","wisdom"]',
     "priority": "core", "resource_type": "cross_ref", "rank": 6},
    # Three-Level Redemptive History
    {"phase": "theological", "question_text": "What is the bottom level — personal history?",
     "guidance_text": "Individual experience within the text.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 7},
    {"phase": "theological", "question_text": "What is the middle level — national/corporate history?",
     "guidance_text": "Israel, the church, the covenant community.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 8},
    {"phase": "theological", "question_text": "What is the top level — redemptive history?",
     "guidance_text": "God's overarching plan of salvation.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 9},
    # Core Theological Questions
    {"phase": "theological", "question_text": "What does this passage reveal about God — his character, will, and ways?",
     "guidance_text": "Theology proper.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 10},
    {"phase": "theological", "question_text": "What does this passage reveal about humanity — our need, sin, and dignity?",
     "guidance_text": "Anthropology.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 11},
    {"phase": "theological", "question_text": "What does this passage reveal about the remedy — grace, Christ, the Spirit?",
     "guidance_text": "Soteriology, Christology, pneumatology.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 12},
    # 6B: Systematic & Biblical Theology
    {"phase": "theological", "question_text": "Are there any systematic theology issues to examine?",
     "guidance_text": "Doctrine this passage teaches, presupposes, or illustrates.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 13},
    {"phase": "theological", "question_text": "Does this connect to a locus of systematic theology?",
     "guidance_text": "Theology proper, Christology, pneumatology, soteriology, ecclesiology, eschatology.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 14},
    {"phase": "theological", "question_text": "Are there biblical theology themes that arc across the canon?",
     "guidance_text": "Themes that need examination here.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 15},
    # 6C: Historical Theology
    {"phase": "theological", "question_text": "Are there significant writings from the church fathers that illuminate this passage?",
     "guidance_text": "Patristic interpretation.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 16},
    {"phase": "theological", "question_text": "Are there confessional documents that reference this passage?",
     "guidance_text": "Westminster Standards, Three Forms of Unity, Second Helvetic, etc.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 17},
    {"phase": "theological", "question_text": "How have major interpreters understood this text?",
     "guidance_text": "Augustine, Calvin, Owen, Edwards, Hodge, Murray, etc.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 18},
    {"phase": "theological", "question_text": "Is there a historical controversy connected to this passage?",
     "guidance_text": "Something the congregation should know about.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 19},

    # ── COMMENTARY (Phase 8) ──
    {"phase": "commentary", "question_text": "What specific questions remain unanswered after my own exegetical work?",
     "guidance_text": "Don't browse — go in with targeted questions. Don't spend all week reading commentaries.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 1},
    {"phase": "commentary", "question_text": "Do the commentaries confirm or challenge my exegetical conclusions?",
     "guidance_text": "Compare your work to the scholars.", "genre_tags": "[]",
     "priority": "core", "resource_type": "commentary", "rank": 2},
    {"phase": "commentary", "question_text": "Is there a consensus reading I'm departing from — and can I justify it?",
     "guidance_text": "If you disagree with the majority, know why.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "commentary", "rank": 3},

    # ── EXEGETICAL POINT (Phase 9) ──
    {"phase": "exegetical_point", "question_text": "What question is this text designed to answer about God?",
     "guidance_text": "Robinson's Subject — the TOPIC of the passage.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 1},
    {"phase": "exegetical_point", "question_text": "What is the ONE thing this passage is about?",
     "guidance_text": "The unifying center.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 2},
    {"phase": "exegetical_point", "question_text": "What is this passage saying about the subject?",
     "guidance_text": "Robinson's Complement — what ANSWERS the subject.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 3},
    {"phase": "exegetical_point", "question_text": "What was God saying through his Spirit through the author to the recipients?",
     "guidance_text": "The Exegetical Point (EP) = Subject + Complement as a single sentence.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 4},
    {"phase": "exegetical_point", "question_text": "Is the proposed EP a simple sentence?",
     "guidance_text": "Keep narrowing until it is one propositional sentence.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 5},
    {"phase": "exegetical_point", "question_text": "Is the EP propositional — can it be affirmed or denied?",
     "guidance_text": "It must be a claim, not a topic.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 6},
    {"phase": "exegetical_point", "question_text": "Does the EP relate every sentence in the passage to the unifying theme?",
     "guidance_text": "Every part should connect.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 7},
    {"phase": "exegetical_point", "question_text": "What is the internal logical flow of the text?",
     "guidance_text": "The exegetical outline — how the argument progresses.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 8},
    {"phase": "exegetical_point", "question_text": "Does every point in the outline support the EP?",
     "guidance_text": "Each point should advance the exegetical idea.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 9},

    # ── FCF + HOMILETICAL (Phase 10) ──
    # FCF
    {"phase": "fcf_homiletical", "question_text": "What spiritual concern(s) did the text address in its original context?",
     "guidance_text": "Chapell Q2 — the original FCF.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 1},
    {"phase": "fcf_homiletical", "question_text": "What spiritual concerns do listeners share with the original audience?",
     "guidance_text": "Chapell Q3 — the bridge to today.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 2},
    {"phase": "fcf_homiletical", "question_text": "What is the depravity factor? What in humanity rebels against this text?",
     "guidance_text": "The human condition that necessitates grace.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 3},
    # HP/THT
    {"phase": "fcf_homiletical", "question_text": "What is God through me saying to his people today?",
     "guidance_text": "The Homiletical Point (HP) / Take-Home Truth (THT).", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 4},
    {"phase": "fcf_homiletical", "question_text": "Is the HP based on the EP?",
     "guidance_text": "The homiletical point must grow from the exegetical point.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 5},
    {"phase": "fcf_homiletical", "question_text": "Is it written in the 2nd person — addressed to 'you'?",
     "guidance_text": "A pastor heralds to his people, not to anonymous 'someone.'", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 6},
    {"phase": "fcf_homiletical", "question_text": "Is it sharp? Will people remember the point on Wednesday?",
     "guidance_text": "It should get under the skin.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 7},
    {"phase": "fcf_homiletical", "question_text": "Does the HP read Christologically?",
     "guidance_text": "A christless sermon can live in a synagogue but ought never among the blood-bought sheep.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 8},
    # Purpose & Application
    {"phase": "fcf_homiletical", "question_text": "What should happen in the listeners as a result of hearing this sermon?",
     "guidance_text": "Robinson's sermon purpose.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 9},
    {"phase": "fcf_homiletical", "question_text": "What does God require of the hearers of this passage?",
     "guidance_text": "The divine imperative.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 10},
    {"phase": "fcf_homiletical", "question_text": "How does the gospel ENABLE obedience to what God requires?",
     "guidance_text": "Chapell's redemptive addition — grace empowers.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 11},
    {"phase": "fcf_homiletical", "question_text": "What holy affections should this text stir?",
     "guidance_text": "Edwards: delight, hatred of sin, hope, gratitude, compassion, fear, longing.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 12},

    # ── SERMON CONSTRUCTION (Phase 11) ──
    {"phase": "sermon_construction", "question_text": "What is the sermon title?",
     "guidance_text": "Short, memorable, connected to the HP.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 1},
    {"phase": "sermon_construction", "question_text": "What type of introduction will you use?",
     "guidance_text": "Front Porch, Challenge, Mystery, Examination, Paradox, Occasion, Quote, Question, Short Story, Ramrod. Must contain the FCF.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 2},
    {"phase": "sermon_construction", "question_text": "For each main point: What is the ORIENTATION?",
     "guidance_text": "Where are we in the text, the sermon, in time/geography/logic?", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 3},
    {"phase": "sermon_construction", "question_text": "For each main point: What is the EXPLANATION?",
     "guidance_text": "Prove it. Geography, customs, names, history, theology, language.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 4},
    {"phase": "sermon_construction", "question_text": "For each main point: What OBJECTIONS might the audience have?",
     "guidance_text": "Validate against emotional or intellectual doubts.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 5},
    {"phase": "sermon_construction", "question_text": "For each main point: What ILLUSTRATION will you use?",
     "guidance_text": "Frame a picture. Slip in, shed the light, get out.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 6},
    {"phase": "sermon_construction", "question_text": "For each main point: What is the APPLICATION?",
     "guidance_text": "So what? Build around the vision of God and the FCF. What will this look like fleshed out?", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 7},
    {"phase": "sermon_construction", "question_text": "For each transition: Does it tie into the HP & FCF?",
     "guidance_text": "Summarize previous point, introduce next smoothly.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 8},
    {"phase": "sermon_construction", "question_text": "How could someone misunderstand, over-apply, or under-apply this?",
     "guidance_text": "Anticipate misreadings.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 9},
    {"phase": "sermon_construction", "question_text": "What would a church characterized by this truth look like?",
     "guidance_text": "Envision corporate transformation.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 10},
    {"phase": "sermon_construction", "question_text": "How would you minister this truth to the depressed, lonely, angry, arrogant?",
     "guidance_text": "Pastoral sensitivity — different hearers need different emphasis.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 11},
    {"phase": "sermon_construction", "question_text": "Three real-life situations where this truth gives stability and hope.",
     "guidance_text": "Concrete, specific, felt.", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 12},

    # ── EDIT & PRAY (Phase 12) ──
    {"phase": "edit_pray", "question_text": "Have I been faithful to the text?",
     "guidance_text": "The most basic question.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 1},
    {"phase": "edit_pray", "question_text": "Am I hitting the head but missing the heart?",
     "guidance_text": "Edwards: true affections engage the mind AND the heart.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 2},
    {"phase": "edit_pray", "question_text": "Is this a lecture or a sermon?",
     "guidance_text": "Chapell: does it have an FCF?", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 3},
    {"phase": "edit_pray", "question_text": "Are the people going to be spurred on toward loving God and His glory?",
     "guidance_text": "The ultimate purpose.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 4},
    {"phase": "edit_pray", "question_text": "Have I read this missiologically?",
     "guidance_text": "Does the sermon have gospel reach?", "genre_tags": "[]",
     "priority": "supplemental", "resource_type": "none", "rank": 5},
    {"phase": "edit_pray", "question_text": "Have I given tangible ways to apply God's word this week?",
     "guidance_text": "Perkins: practical uses.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 6},
    {"phase": "edit_pray", "question_text": "Have I bound up the wounded? Preached freedom to captives? Brought good news to the poor?",
     "guidance_text": "Isaiah 61 — the ministry of the Word.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 7},
    {"phase": "edit_pray", "question_text": "Does the intro have a Fallen Condition Focus?",
     "guidance_text": "Non-negotiable per Chapell.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 8},
    {"phase": "edit_pray", "question_text": "Have I landed the sermon — is it tied up so people remember?",
     "guidance_text": "The conclusion must land.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 9},
    {"phase": "edit_pray", "question_text": "Pray over the sermon.",
     "guidance_text": "Clarity, conviction, that it hits the heart, teaches the mind, proclaims Christ and Him crucified.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 10},
    {"phase": "edit_pray", "question_text": "Ruthlessly edit.",
     "guidance_text": "Not everything that can be said needs to be said. A clear sermon is better than a long sermon.", "genre_tags": "[]",
     "priority": "core", "resource_type": "none", "rank": 11},
]


def seed_question_bank(db):
    """Populate question_bank table with all questions. Idempotent — clears and reinserts."""
    conn = db._conn()
    conn.execute("DELETE FROM question_bank")
    for q in QUESTIONS:
        conn.execute("""
            INSERT INTO question_bank (phase, question_text, guidance_text, genre_tags, priority, resource_type, rank)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        """, (q["phase"], q["question_text"], q["guidance_text"], q["genre_tags"],
              q["priority"], q["resource_type"], q["rank"]))
    conn.commit()
    conn.close()


if __name__ == "__main__":
    import sys
    import os
    sys.path.insert(0, os.path.dirname(__file__))
    from companion_db import CompanionDB

    db_path = os.path.join(os.path.dirname(__file__), "workbench.db")
    db = CompanionDB(db_path)
    db.init_db()
    seed_question_bank(db)
    print(f"Seeded {len(QUESTIONS)} questions into {db_path}")
